name: Docker Core Build and Push

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - "src/main/java/spot/fakeApi/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./fakeApi

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./fakeApi

      - name: List files in build/libs
        run: ls -R build/libs
        working-directory: ./fakeApi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./fakeApi
          file: ./fakeApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fakeApi:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Save Core GITHUB_SHA
        run: echo ${{ github.sha }} > core_sha.txt

      - name: Upload Core SHA file
        uses: actions/upload-artifact@latest
        with:
          name: core_sha
          path: core_sha.txt
